### ISSUE TITLE
Integrate CI

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/teachy#12]
You'll have to wait till I actually commit at least something.

choose between:
* codeship
* circle ci
* travis ci

**Comment by wafflestomper** [comment]
I choose circle.  Because it is a shape.  With no sides.  Circles... where do I begin...?

**Comment by mattzollinhofer** [comment]
good choice and solid logic :-)  this might help get you started: http://bfy.tw/18WQ

**Comment by wafflestomper** [comment]
So funny... http://bfy.tw/503r <-- do better.


--------------------------------
Brian Zollinhofer
St. Christopher's School
Middle School Instructional Technologist
--------------------------------

**Comment by mattzollinhofer** [comment]
hehehehe, I also wanted to actually send that to someone who wouldn't be
offended :-)

**Comment by wafflestomper** [comment]
Yeah, that is one of those sites that is awesome and you can never use it...

I've also decided on Travis CI unless you have a strong feeling another way.



--------------------------------
Brian Zollinhofer
St. Christopher's School
Middle School Instructional Technologist
--------------------------------

**Comment by mattzollinhofer** [comment]
Sounds good

**Comment by mattzollinhofer** [comment]
Where's my CI!! :smile:

**Comment by wafflestomper** [comment]
Oh... I just chose the CI. I have no idea how to make it. Also I'm in a cabin in the woods with no internet, so there's that...

**Comment by mattzollinhofer** [comment]
GET ON IT!!! :-)

**Comment by wafflestomper** [comment]
;)
