### ISSUE TITLE
Assignment Model

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/teachy#2]
Attributes
 - [ ] `status` (enum)
 - [x] `points_earned` (int)
 - [x] `points_possible` (int)
 - [x] `order` (int)
 - [x] `due_at` (date_time)
 - [x] `completed_at` (date_time)

**Comment by wafflestomper** [comment]
due date?

**Comment by mattzollinhofer** [comment]
@wafflestomper I added completed date. Does it matter when the student started?

**Comment by mattzollinhofer** [comment]
don't think I need to store status for now, will just calculate it as needed I think

**Comment by wafflestomper** [comment]
Don't need "started date"
