### ISSUE TITLE
Only teachers are created, no students

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/teachy#33]

**Comment by mattzollinhofer** [comment]
Closing for now as we talked about. If you decide we don't want to show grades, just let me know. I'd rather not build in the preferences at this point if we don't have to.

**Comment by wafflestomper** [comment]
I talked with my boss and he didn't seem to have an issue with grades so
for now I think we are ok.


--------------------------------
Brian Zollinhofer
St. Christopher's School
Middle School Instructional Technologist
--------------------------------

**Comment by mattzollinhofer** [comment]
Embarrassing, totally commented on the wrong issue :-(

**Comment by mattzollinhofer** [comment]
Pretty sure this is not an issue any more, not sure when it got fixed.
