### ISSUE TITLE
Student Model

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/teachy#6]
Attributes:
 - [x] `nickname` (string)   //no one goes by their first name, but it is helpful to have for records)
 - [x] `grade level` (int)   // graduation year
 - [ ] `course` (has_many)
 - [x] `user` (belongs_to)

**Comment by wafflestomper** [comment]
Possible ability to click an assignment that they have finished but the teacher hasn't inputted a grade for yet?

**Comment by mattzollinhofer** [comment]
This sounds like 'completion state' for the assignment model (we need to start specifying issues for some of the actions you're taking about). That'll probably come once we start building the models.
