### ISSUE TITLE
Teacher Model

### ISSUE THREAD

**Issue by mattzollinhofer** [mattzollinhofer/teachy#7]
- [ ] `courses` (has_and_belongs_to_many)
- [ ] `students` (has_many through courses)
- [ ] `user` (belongs_to)

**Comment by wafflestomper** [comment]
It would be interesting for the teacher to be able to see when/how often a student/parent looks at the page (just for informational needs).

**Comment by mattzollinhofer** [comment]
Yeah, I think that'd be a phase 2 feature - add an issue called course views model maybe?
